import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AppWrapper } from "./appwrapper";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <div className="lg:px-[60px] px-2">
          <AppWrapper>{children}</AppWrapper>
        </div>
      </body>
    </html>
  );
}
