import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "summerville",
  description:
    "We are a digital product agency that specializes in creating exceptional digital experiences.",
  openGraph: {
    title: "summerville",
    description:
      "We are a digital product agency that specializes in creating exceptional digital experiences.",
    url: "https://summerville.agency",
    siteName: "summerville",
    images: [
      {
        url: "/_next/static/media/summerville2.png",
        width: 1200,
        height: 630,
        alt: "Summerville Agency",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
    shortcut: "/favicon-32x32.png",
  },
  themeColor: "#000000",
  manifest: "/site.webmanifest",
  robots: {
    index: true,
    follow: true,
    nocache: false,
    noimageindex: false,
    noarchive: false,
    nosnippet: false,
  },
  keywords: [
    "digital product agency",
    "web development",
    "mobile app development",
    "UI/UX design",
    "software development",
    "digital marketing",
    "e-commerce solutions",
    "SEO services",
    "branding",
    "digital strategy",
    "custom software solutions",
    "digital transformation",
    "cloud solutions",
    "API development",
    "content management systems",
    "e-learning platforms",
    "SaaS development",
    "e-commerce platforms",
    "digital product design",
    "user experience design",
    "user interface design",
    "responsive web design",
    "progressive web apps",
    "cross-platform app development",
    "web application development",
    "mobile application development",
    "digital product strategy",
    "digital product management",
    "digital product design agency",
    "digital product development",
    "digital product agency",
    "digital product solutions",
    "digital product consulting",
    "digital product innovation",
    "digital product engineering",
    "digital product design and development",
    "digital product design and strategy",
    "digital product design and consulting",
    "digital product design and development agency",
    "digital product design and development company",
    "digital product design and development services",
    "digital product design and development solutions",
    "digital product design and development firm",
    "digital product design and development experts",
    "digital product design and development specialists",
    "digital product design and development professionals",
    "digital product design and development team",
  ],
  alternates: {
    canonical: "https://summerville.agency",
    types: {
      "application/rss+xml": "/feed.xml",
      "application/atom+xml": "/atom.xml",
    },
  },
};
